name: build kafkas

on:
  pull_request:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo build and test
        run: |
          rustup default nightly
          rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
          cargo build
          cargo test
          cargo clippy